version: 2.1

jobs:
  setup-test:
    machine:
      image:ubuntu-2204:2022.07.1

    steps:
      - checkout

      # Create the directory if it doesn't exist
      - run:
          name: Create directory
          command: mkdir -p /home/circleci/project

      # Install Composer
      - run:
          name: Install Composer
          command: |
            curl -sS https://getcomposer.org/installer | php -- --install-dir=/home/circleci/project
            echo 'export PATH="$PATH:/home/circleci/project"' >> $BASH_ENV
            source $BASH_ENV

      # Run Composer install
      - run:
          name: Run Composer install
          command: php /home/circleci/project/composer.phar install

      # Run PHP tests
      - run:
          name: Run PHP tests
          command: composer -v

workflows:
  version: 2
  test:
    jobs:
      - build
