version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout

      # Install PHP dependencies
      - run:
          name: Install PHP dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip
            curl -sS https://getcomposer.org/installer | php
            mv composer.phar /usr/local/bin/composer
            composer install

      # Run PHP tests
      - run:
          name: Run PHP tests
          command: |
            phpunit tests

      # Install Node.js and npm
      - run:
          name: Install Node.js and npm
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs

      # Install Jasmine dependencies
      - run:
          name: Install Jasmine dependencies
          command: |
            npm install -g jasmine

      # Run Jasmine tests
      - run:
          name: Run Jasmine tests
          command: |
            # Assuming your Jasmine tests are in a 'spec' directory
            jasmine JASMINE_CONFIG_PATH=jasmine.json

workflows:
  version: 2
  build:
    jobs:
      - build
