version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip
            curl -sS https://getcomposer.org/installer | php
            mv composer.phar /usr/local/bin/composer
            composer install
            ./vendor/bin/phpunit
 
workflows:
  version: 2
  build:
    jobs:
      - build
