version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip
            curl -sS https://getcomposer.org/installer | php -- --install-dir=/home/circleci/project
            cd /home/circleci/project
            php composer.phar install
 
      - run:
          name: Make PHPUnit executable
          command: |
            chmod +x ./vendor/bin/phpunit
 
      - run:
          name: Run PHPUnit tests
          command: |
            ./vendor/bin/phpunit

workflows:
  version: 2
  build:
    jobs:
      - build
