version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16

    steps:
      - checkout

      # Install Node.js dependencies
      - run:
          name: Install Node.js dependencies
          command: npm install

      # Run tests
      - run:
          name: Run Node.js tests
          command: npm test

      # Start Docker daemon
      - setup_remote_docker:
          version: 19.03.13

      # Build Docker image for Node.js
      - run:
          name: Build Docker image for Node.js
          command: |
            docker build -t $DOCKERHUB_USERNAME/uems-image:latest .
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push $DOCKERHUB_USERNAME/uems-image:latest

      # Additional steps for PHP
      - image: cimg/php:8.1
        steps:
          - run:
              name: Install PHP dependencies
              command: |
                sudo apt-get update
                sudo apt-get install -y unzip
                curl -sS https://getcomposer.org/installer | php -- --install-dir=/home/circleci/project
                cd /home/circleci/project
                php composer.phar install

          - run:
              name: Make PHPUnit executable
              command: chmod +x ./vendor/bin/phpunit

          - run:
              name: Run PHPUnit tests
              command: ./vendor/bin/phpunit

workflows:
  version: 2
  test:
    jobs:
      - build
