version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
 
    steps:
      - checkout

      # Install Node.js dependencies
      - run:
          name: Install Node.js dependencies
          command: npm install
 
      # Run Node.js tests
      - run:
          name: Run Node.js tests
          command: npm test
 
      # Install PHP and Composer locally
      - run:
          name: Install PHP dependencies
          command: php -v

 
      # Run PHP tests
      - run:
          name: Run PHP tests
          command: phpunit test

workflows:
  version: 2
  test:
    jobs:
      - build
