version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:8.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip
            curl -sS https://getcomposer.org/installer | php
            composer install
 
      - run:
          name: Run PHPUnit tests
          command: |
            ./vendor/bin/phpunit
 
workflows:
  version: 2
  build:
    jobs:
      - build
