version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:8.x-cli
        environment:
          COMPOSER_HOME: /home/circleci

    steps:
      - checkout
      
      - run:
          name: Install Composer and dependencies
          command: |
            mkdir -p /home/circleci/.composer
            curl -sS https://getcomposer.org/installer | php -- --install-dir=/home/circleci --filename=composer
            /home/circleci/composer install

      - run:
          name: Run PHPUnit tests
          command: ./vendor/bin/phpunit

workflows:
  version: 2
  test:
    jobs:
      - build
