version: 2.1
 
# Define the jobs we want to run for this project
jobs:
  build_and_push:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: 
          name: Install Docker client
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-ce-cli
      - run: 
          name: Build Docker Image
          command: |
            docker build -t $DOCKERHUB_USERNAME/my-python-app-python:${CIRCLE_SHA1} .
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push $DOCKERHUB_USERNAME/my-python-app-python:${CIRCLE_SHA1}
 
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the test job"
 
# Orchestrate our job run sequence
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_push:
        filters:
          branches:
          only: Dockersetup
