version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4-cli
        environment:
          PHP_VERSION: 7.4
          COMPOSER_HOME: /home/circleci

    steps:
      - checkout

      # Install Composer and dependencies
      - run:
          name: Install Composer and dependencies
          command: |
            mkdir -p /home/circleci/.composer
            curl -sS https://getcomposer.org/installer | php -- --install-dir=/home/circleci --filename=composer
            /home/circleci/composer install

      # Run PHPUnit tests
      - run:
          name: Run PHPUnit tests
          command: ./vendor/bin/phpunit

workflows:
  version: 2
  test:
    jobs:
      - build
